### PR TITLE
chore: update dependencies

### PR DESCRIPTION
**Pull request by ahippler**
BREAKING CHANGE: drop node 8 and 10 support

### CODE REVIEW

**Review by malept — CHANGES_REQUESTED** [review]
We appreciate the effort here, but as a policy we do not accept `yarn.lock` changes from untrusted contributors (that is, non-Dependabot, non-members of the Electron org). See https://snyk.io/blog/why-npm-lockfiles-can-be-a-security-blindspot-for-injecting-malicious-modules/ for details.

There also appears to be some non-trivial changes which need some explanation as to why they were made.

**Comment by ahippler** [comment]
@malept how do you want to proceed?

**Comment by malept** [comment]
The Ecosystem WG talked about it and we're going to pass on this PR for the reasons I listed earlier.

**Comment by gjasny** [comment]
And who's going to updates the dependencies when?

**Comment by malept** [comment]
> And who's going to update the dependencies and when?

It's on my list, but it's a long list and I do this in my increasingly limited spare time.

**Pull request closed without merging**
